spring:
  application:
    name: watchservice-agent

  main:
    headless: false

  datasource:
    url: jdbc:sqlite:log.db          # ✅ 프로젝트 루트에 log.db 생성/사용
    driver-class-name: org.sqlite.JDBC
    username: ""                     # SQLite는 보통 계정/비번 없음
    password: ""

  sql:
    init:
      mode: never                    # 스키마 자동 초기화 안 씀 (우리가 코드로 CREATE TABLE 함)

# (선택) 로그 좀 더 보고 싶으면
logging:
  level:
    com.watchserviceagent.watchservice_agent: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.datasource: DEBUG

ai:
  analyze:
    url: http://localhost:8001/api/analyze
  family:
    url: http://localhost:8001/predict
